[2025-08-01T04:28:51.029+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-01T04:28:51.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-01T03:00:00+00:00 [queued]>
[2025-08-01T04:28:51.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-01T03:00:00+00:00 [queued]>
[2025-08-01T04:28:51.058+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-01T04:28:51.066+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_new_file> on 2025-08-01 03:00:00+00:00
[2025-08-01T04:28:51.072+0000] {standard_task_runner.py:63} INFO - Started process 486 to run task
[2025-08-01T04:28:51.075+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_postgres', 'wait_for_new_file', 'scheduled__2025-08-01T03:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_postgres.py', '--cfg-path', '/tmp/tmpxfqkdfho']
[2025-08-01T04:28:51.076+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask wait_for_new_file
[2025-08-01T04:28:51.092+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-01T04:28:51.118+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-01T03:00:00+00:00 [running]> on host 87b19f697adc
[2025-08-01T04:28:51.301+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_new_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-01T03:00:00+00:00'
[2025-08-01T04:28:51.302+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-01T04:28:51.310+0000] {python.py:75} INFO - Poking callable: <function check_new_file at 0x7fecb6d439a0>
[2025-08-01T04:28:51.406+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2025-08-01T04:28:51.406+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-01T04:28:51.414+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_to_postgres, task_id=wait_for_new_file, run_id=scheduled__2025-08-01T03:00:00+00:00, execution_date=20250801T030000, start_date=20250801T042851, end_date=20250801T042851
[2025-08-01T04:28:51.447+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-01T04:28:51.469+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-01T04:28:51.470+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
