[2025-08-28T05:00:00.662+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T05:00:00.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T04:00:00+00:00 [queued]>
[2025-08-28T05:00:00.685+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T04:00:00+00:00 [queued]>
[2025-08-28T05:00:00.686+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T05:00:00.694+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_new_file> on 2025-08-28 04:00:00+00:00
[2025-08-28T05:00:00.699+0000] {standard_task_runner.py:63} INFO - Started process 2602 to run task
[2025-08-28T05:00:00.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_postgres', 'wait_for_new_file', 'scheduled__2025-08-28T04:00:00+00:00', '--job-id', '656', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_postgres.py', '--cfg-path', '/tmp/tmpl4r1jnsj']
[2025-08-28T05:00:00.703+0000] {standard_task_runner.py:91} INFO - Job 656: Subtask wait_for_new_file
[2025-08-28T05:00:00.715+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T05:00:00.740+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T04:00:00+00:00 [running]> on host c3d91d0460b0
[2025-08-28T05:00:00.805+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_new_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-28T04:00:00+00:00'
[2025-08-28T05:00:00.806+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T05:00:00.930+0000] {python.py:75} INFO - Poking callable: <function check_new_file at 0x7ff845fbbe20>
[2025-08-28T05:00:01.029+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2025-08-28T05:00:01.029+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T05:00:01.036+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_to_postgres, task_id=wait_for_new_file, run_id=scheduled__2025-08-28T04:00:00+00:00, execution_date=20250828T040000, start_date=20250828T050000, end_date=20250828T050001
[2025-08-28T05:00:01.074+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-28T05:00:01.094+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-28T05:00:01.095+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
